spring:
  application:
    name: DocumentReaderService
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
  datasource:
    url: jdbc:postgresql://localhost:5432/ai
    username: ai
    password: ai

server:
  port: 7070

